# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(611, 430)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setObjectName("start_pushButton")
        self.gridLayout.addWidget(self.start_pushButton, 0, 0, 1, 1)
        self.suspend_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.suspend_pushButton.setObjectName("suspend_pushButton")
        self.gridLayout.addWidget(self.suspend_pushButton, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timepiece_label = QtWidgets.QLabel(self.centralwidget)
        self.timepiece_label.setObjectName("timepiece_label")
        self.horizontalLayout_2.addWidget(self.timepiece_label)
        self.timepiece_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.timepiece_lineEdit.setObjectName("timepiece_lineEdit")
        self.horizontalLayout_2.addWidget(self.timepiece_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.process_label = QtWidgets.QLabel(self.centralwidget)
        self.process_label.setTextFormat(QtCore.Qt.PlainText)
        self.process_label.setObjectName("process_label")
        self.horizontalLayout.addWidget(self.process_label)
        self.process_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.process_lineEdit.setEnabled(False)
        self.process_lineEdit.setObjectName("process_lineEdit")
        self.horizontalLayout.addWidget(self.process_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.times_label = QtWidgets.QLabel(self.centralwidget)
        self.times_label.setObjectName("times_label")
        self.horizontalLayout_3.addWidget(self.times_label)
        self.times_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.times_lineEdit.setEnabled(False)
        self.times_lineEdit.setObjectName("times_lineEdit")
        self.horizontalLayout_3.addWidget(self.times_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ready_label = QtWidgets.QLabel(self.centralwidget)
        self.ready_label.setObjectName("ready_label")
        self.verticalLayout.addWidget(self.ready_label)
        self.ready_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.ready_tableWidget.setEnabled(False)
        self.ready_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ready_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ready_tableWidget.setObjectName("ready_tableWidget")
        self.ready_tableWidget.setColumnCount(2)
        self.ready_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        item.setFont(font)
        self.ready_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ready_tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.ready_tableWidget)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.in_label = QtWidgets.QLabel(self.centralwidget)
        self.in_label.setObjectName("in_label")
        self.verticalLayout_2.addWidget(self.in_label)
        self.in_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.in_tableWidget.setEnabled(False)
        self.in_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.in_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.in_tableWidget.setObjectName("in_tableWidget")
        self.in_tableWidget.setColumnCount(2)
        self.in_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        item.setFont(font)
        self.in_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.in_tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.in_tableWidget)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.out_label = QtWidgets.QLabel(self.centralwidget)
        self.out_label.setObjectName("out_label")
        self.verticalLayout_3.addWidget(self.out_label)
        self.out_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.out_tableWidget.setEnabled(False)
        self.out_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.out_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.out_tableWidget.setObjectName("out_tableWidget")
        self.out_tableWidget.setColumnCount(2)
        self.out_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        item.setFont(font)
        self.out_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.out_tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.out_tableWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wait_label = QtWidgets.QLabel(self.centralwidget)
        self.wait_label.setObjectName("wait_label")
        self.verticalLayout_4.addWidget(self.wait_label)
        self.wait_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.wait_tableWidget.setEnabled(False)
        self.wait_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.wait_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.wait_tableWidget.setObjectName("wait_tableWidget")
        self.wait_tableWidget.setColumnCount(2)
        self.wait_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        item.setFont(font)
        self.wait_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wait_tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_4.addWidget(self.wait_tableWidget)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.OpenFile = QtWidgets.QAction(mainWindow)
        self.OpenFile.setObjectName("OpenFile")
        self.toolBar.addAction(self.OpenFile)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "时间片轮转调度"))
        self.start_pushButton.setText(_translate("mainWindow", "开始调度"))
        self.start_pushButton.setShortcut(_translate("mainWindow", "Enter"))
        self.suspend_pushButton.setText(_translate("mainWindow", "暂停调度"))
        self.suspend_pushButton.setShortcut(_translate("mainWindow", "Esc"))
        self.timepiece_label.setText(_translate("mainWindow", "时间片大小："))
        self.timepiece_lineEdit.setPlaceholderText(_translate("mainWindow", "ms"))
        self.process_label.setText(_translate("mainWindow", "当前运行进程："))
        self.times_label.setText(_translate("mainWindow", "累计执行时间片个数："))
        self.ready_label.setText(_translate("mainWindow", "就绪队列"))
        item = self.ready_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "进程名"))
        item = self.ready_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "执行进度"))
        self.in_label.setText(_translate("mainWindow", "输入等待队列"))
        item = self.in_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "进程名"))
        item = self.in_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "执行进度"))
        self.out_label.setText(_translate("mainWindow", "输出等待队列"))
        item = self.out_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "进程名"))
        item = self.out_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "执行进度"))
        self.wait_label.setText(_translate("mainWindow", "其他等待队列"))
        item = self.wait_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "进程名"))
        item = self.wait_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "执行进度"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.OpenFile.setText(_translate("mainWindow", "打开文件"))
        self.OpenFile.setToolTip(_translate("mainWindow", "Ctrl+F"))
        self.OpenFile.setShortcut(_translate("mainWindow", "Ctrl+F"))

